name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_tests.txt
    - name: Lint with flake8
      run: |
        flake8 custom_components/carson/ tests/
    - name: Lint with pylint
      run: |
        pylint --rcfile=setup.cfg custom_components/carson/ tests/
    - name: Test with pytest
      run: |
        python -m pytest --cov --cov-report term-missing --cov-config=setup.cfg
    - name: Coveralls
      # only Upload for a single version
      if: ${{ matrix.python-version == 3.7 }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        coveralls